### ISSUE TITLE
Why is the library compiled with SDK Level 23?

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#40]
Would love to know what the exact reason is that causes you to compile with SDK Level 23, perhaps there's a workaround to allow for more compatibility, this has started causing issues on our distribution. 

We tried hard to keep building our app with SDK 16, but it was impossible to do so once we included MobFox. None of the other AdNetwork's SDKs we've used demand such high API Level.

CC: @aldenml

**Comment by nabriski** [comment]
Our min sdk version is 15:

``` gradle
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName version
    }
```

**Comment by aldenml** [comment]
do you specify `compileSdkVersion`? Are you using appcompat for API `23`?

**Comment by nabriski** [comment]
Yes we have `compileSdkVersion 23` and `compile 'com.android.support:appcompat-v7:23.1.1'`

**Comment by aldenml** [comment]
The fact that you are using `appcompat` pull a lot of material design resource references, then it mandates that every client requires that minimum SDK in order to compile. This a potentially dangerous situation, since we need to heavily rely in lint, hardly a good solution. How reasonable is to you to work around this?

**Comment by nabriski** [comment]
Our Android dev will be back in the office next week (Sunday), I will show him this issue ans we'll discuss it.

**Comment by aldenml** [comment]
Thank
